[package]
name = "sentry-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "*"
sentry = { version = "0.32.1", features = ["UNSTABLE_metrics"] }
